[package]
name    = "indicators"
version.workspace = true
edition.workspace = true

[dependencies]
ts_core    = { workspace = true }
data       = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
anyhow     = { workspace = true }
sha2       = { workspace = true }
tracing    = { workspace = true }
